/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author PC
 */
public class PantallaInicialProductor extends javax.swing.JFrame {

    /**
     * Creates new form PantallaInicial
     */
    public PantallaInicialProductor() {
        initComponents();
        this.setTitle("Sistema Residuos Toxicos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        selectRegistrarRes = new javax.swing.JButton();
        btnSolicitaTras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectRegistrarRes.setContentAreaFilled(false);
        selectRegistrarRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectRegistrarResActionPerformed(evt);
            }
        });
        jPanel1.add(selectRegistrarRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 183, 200, 50));

        btnSolicitaTras.setContentAreaFilled(false);
        btnSolicitaTras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitaTrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnSolicitaTras, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 200, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantalla Productor - Residuos Tóxicos.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 720, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selectRegistrarResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectRegistrarResActionPerformed
       new RegistraResiduosFrm().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_selectRegistrarResActionPerformed

    private void btnSolicitaTrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitaTrasActionPerformed
       new SolicitarTrasladosFrm().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnSolicitaTrasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSolicitaTras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton selectRegistrarRes;
    // End of variables declaration//GEN-END:variables
}
