/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author PRIDE ANACONDA
 */
public class RegistraResiduos extends javax.swing.JFrame {

    /**
     * Creates new form RegistraResiduosFrm
     */
    DefaultListModel<String> modelDisponibles = new DefaultListModel<>(); 
    DefaultListModel<String> modelSeleccionados = new DefaultListModel<>(); 
    public RegistraResiduos() {
        initComponents();
        quimicosDisponiblesList.setModel(modelDisponibles);
        quimicosReservadosList.setModel(modelSeleccionados);
        inicializaLista();
        this.setTitle("Registro Residuos");
        
    }
    public void inicializaLista(){
                
        modelDisponibles.addElement("Cloro");
        modelDisponibles.addElement("Cianuro");
        modelDisponibles.addElement("Plomo");
        modelDisponibles.addElement("Amoniaco");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        nombreTxt = new javax.swing.JTextField();
        codigoTxt = new javax.swing.JTextField();
        agregarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        quimicosDisponiblesList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        quimicosReservadosList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreTxt.setBorder(null);
        mainPanel.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 220, 30));

        codigoTxt.setBorder(null);
        mainPanel.add(codigoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 220, 30));

        agregarBtn.setText("Agregar");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });
        mainPanel.add(agregarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        eliminarBtn.setText("Eliminar");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });
        mainPanel.add(eliminarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        quimicosDisponiblesList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(quimicosDisponiblesList);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 90, 140));

        quimicosReservadosList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(quimicosReservadosList);

        mainPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 90, 140));
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        btnRegresar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        mainPanel.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 120, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        mainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setText("Codigo:");
        mainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel4.setText("Registro de Residuos");
        mainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        mainPanel.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        new PantallaInicialProductor().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        // TODO add your handling code here:
        if(quimicosDisponiblesList.getSelectedIndex() !=-1){
            agregaAListaSeleccionados();
            eliminaDeListaDisponibles();
        }else if(quimicosReservadosList.getSelectedIndex() !=-1){
            mostrarMensaje("No puedes agregar ningun quimico aquí", "Error", "Error al Agregar");
        } else {
            mostrarMensaje("No seleccionó ningun quimico", "Error", "Error al Agregar");
        }
            
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        // TODO add your handling code here:
        if(quimicosReservadosList.getSelectedIndex() !=-1){
           agregaAListaDisponibles();
           eliminaDeListaSeleccionados(); 
        }else if(quimicosDisponiblesList.getSelectedIndex() !=-1){
            mostrarMensaje("No puedes eliminar un quimico de aquí", "Error", "Error al Eliminar");
        } else{
            mostrarMensaje("No seleccionó ningun quimico", "Error", "Error al Eliminar");
        }

    }//GEN-LAST:event_eliminarBtnActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        JOptionPane.showMessageDialog(null, "¡Se ha guardado con exito!");
    }//GEN-LAST:event_btnGuardarActionPerformed
    public void eliminaDeListaDisponibles(){
       modelDisponibles.removeElementAt(quimicosDisponiblesList.getSelectedIndex());
    }
    public void agregaAListaDisponibles(){
       modelDisponibles.addElement(quimicosReservadosList.getSelectedValue());
    }
    public void eliminaDeListaSeleccionados(){
       modelSeleccionados.removeElementAt(quimicosReservadosList.getSelectedIndex());
    }
    public void agregaAListaSeleccionados(){
       modelSeleccionados.addElement(quimicosDisponiblesList.getSelectedValue());
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JList<String> quimicosDisponiblesList;
    private javax.swing.JList<String> quimicosReservadosList;
    // End of variables declaration//GEN-END:variables


    public void mostrarMensaje (String mensaje, String tipo, String titulo){
        JOptionPane optionPane = new JOptionPane(mensaje);
        if(tipo.equals("Info")){
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        }
        else if(tipo.equals("Error")){
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
        }
        JDialog dialog = optionPane.createDialog(titulo);
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);      
    }

}
