/*
 *
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.validaciones.VehiculoNegocio;
import entitys.SolicitudTrasladoModel;
import entitys.UsuarioModel;
import entitys.VehiculoModel;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author xfs85
 */
public class RegistrarTrasladoFrm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarTraslado
     */
    UsuarioModel usuarioActual;
    SolicitudTrasladoModel solicitudActual;
    VehiculoNegocio vn = new VehiculoNegocio();
    DefaultTableModel tableModel = new DefaultTableModel();
    private javax.swing.JCheckBox JCheckBox;

    public RegistrarTrasladoFrm(UsuarioModel usuario, SolicitudTrasladoModel solicitud) {
        this.usuarioActual = usuario;
        this.solicitudActual = solicitud;
        initComponents();

        tableModel.addColumn("");
        tableModel.addColumn("Linea");
        tableModel.addColumn("Marca");
        tableModel.addColumn("Modelo");
        tableModel.addColumn("Tipo");
        JCheckBox = new javax.swing.JCheckBox();
        jTable2.setModel(tableModel);
        cargarVehiculos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnRegistrarTraslado = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        fechaLlegadaPicker = new com.github.lgooddatepicker.components.DatePicker();
        txtKm = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTratamiento = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Boolean(false), null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 127, 280, 190));

        btnRegistrarTraslado.setContentAreaFilled(false);
        btnRegistrarTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarTrasladoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 160, 30));

        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 33, 40, 30));
        jPanel1.add(fechaLlegadaPicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));
        jPanel1.add(txtKm, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 50, -1));
        jPanel1.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 50, -1));

        txtTratamiento.setColumns(20);
        txtTratamiento.setRows(5);
        jScrollPane1.setViewportView(txtTratamiento);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 250, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pantalla nueva registrar traslado 2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cargarVehiculos() {
        List<VehiculoModel> vehiculos = vn.obtenerVehiculos(this.usuarioActual.getId());
        tableModel.setRowCount(0);

        for (VehiculoModel vehiculo : vehiculos) {
            Object[] fila = {
                
                false,
                vehiculo.getLinea(),
                vehiculo.getMarca(),
                vehiculo.getMarca(),
                vehiculo.getModelo()
            };
            tableModel.addRow(fila);
            
            addCheckbox(0,jTable2);
        }

    
    }
    
    public void addCheckbox(int column, JTable table){
        TableColumn tc = table.getColumnModel().getColumn(column);
        tc.setCellEditor(table.getDefaultEditor(Boolean.class));
        tc.setCellRenderer(table.getDefaultRenderer(Boolean.class));
    }
    
    public boolean isSelected(int row, int column, JTable table){
        return table.getValueAt(row, column) != null;
    }

    private void btnRegistrarTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarTrasladoActionPerformed
        JOptionPane.showMessageDialog(null, "Registro Exitoso");
        new PantallaInicial(this.usuarioActual).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarTrasladoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new SolicitudesAsignadasFrm(this.usuarioActual).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarTraslado;
    private javax.swing.JButton btnVolver;
    private com.github.lgooddatepicker.components.DatePicker fechaLlegadaPicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtKm;
    private javax.swing.JTextArea txtTratamiento;
    // End of variables declaration//GEN-END:variables
}
